#!/bin/bash -e

cd $(dirname $0)/..

# Copy the service account json file to the keys directory
cp ${GOOGLE_SERVICE_ACCOUNT_JSON} ./keys/service_account.json
printf "Copied service account json to keys directory ✅ \n"

